# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Tests

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2', '8.5']

    steps:
      - name: Check out the app
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: imagick
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Validate Composer metadata
        run: composer validate --strict

      - name: Run unit tests
        run: composer test

      - name: Run static analysis
        run: composer analyse
